### PR TITLE
Add a force capitalization option

### PR DESCRIPTION
**Pull request by ShadiestGoat**
This is a PR that adds a setting to force capitalize all text. I believe this is useful, since most of the time you want to write in caps, but I personally don't wanna turn on caps lock every time I want to use this.

### CODE REVIEW

**Comment by FxllenCode** [comment]
I'm unsure how this is relevant to the plugin. Could you explain it?

**Comment by ShadiestGoat** [comment]
Usually when making a 'no bitches' meme, all content is capitalized, which is why I think it's relevant

**Comment by FxllenCode** [comment]
@ShadiestGoat okay, I think I understand. Thanks for clarifying! I'll test this out right now.

**Comment by FxllenCode** [comment]
Thanks for contributing!

**Pull request merged**
